Traceback (most recent call last):
  File "./verify/check-realms", line *, in testNegotiate
    self.configure_kerberos()
*
CalledProcessError: Command '<script>' returned non-zero exit status 2
